export default {
  jwtTokenSecret: {
    doc: "The JWT token signing algorithm secret",
    format: "String",
    default: "just-a-default-secret",
    nullable: false,
    env: "JWT_SECRET",
  },
  port: {
    doc: "The API listening port. By default is 0 (ephemeral) which serves as a dynamic port for testing purposes. For production use, a specific port must be assigned",
    format: "Number",
    default: 0,
    nullable: true,
    env: "PORT",
  },
  apiPrefix: {
    doc: "The root endpoint of the API",
    format: "String",
    default: "/",
    nullable: false,
    env: "API_PREFIX",
  },
  DB: {
    userName: {
      doc: "The DB connection username",
      format: "String",
      default: "myuser",
      nullable: false,
      env: "DB_USERNAME",
    },
    port: {
      doc: "The DB port",
      format: "Number",
      default: "54320",
      nullable: false,
      env: "DB_PORT",
    },
    host: {
      doc: "The DB cluster host URL",
      format: "String",
      default: "localhost",
      nullable: false,
      env: "DB_HOST",
    },
    password: {
      doc: "The DB connection password. Don't put production code here",
      format: "String",
      default: "myuserpassword",
      nullable: false,
      env: "DB_PASSWORD",
    },
    dbName: {
      doc: "The default database name",
      format: "String",
      default: "shop",
      nullable: false,
      env: "DB_NAME",
    },
    protocol: {
      doc: "The DB connection protocol",
      format: "String",
      default: "mongodb",
      nullable: false,
      env: "DB_PROTOCOL",
    },
  },
};
